AWSTemplateFormatVersion: "2010-09-09"
Description: 'Provision resources for the landing page of codemonger'

Parameters:
  LandingPageAliases:
    Description: 'Domain names (aliases) of the landing page of codemonger'
    Type: 'CommaDelimitedList'
    Default: 'codemonger.io'
  LandingPageDomainCertificateArn:
    Description: 'ARN of the certificate for the domain ownership, that is issued by Amazon Cerficate Manager (ACM)'
    Type: 'String'
  ProjectTag:
    Description: 'Value of the "project" tag'
    Type: 'String'
    Default: 'codemonger'

Resources:
  CodeMongerLandingPageBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
        - Key: 'project'
          Value: !Ref ProjectTag

  CodeMongerLandingPageBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref CodeMongerLandingPageBucket
      PolicyDocument:
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:GetObject'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CodeMongerLandingPageOriginAccessIdentity}'
            Resource:
              - !Sub '${CodeMongerLandingPageBucket.Arn}/*'

  CodeMongerLandingPageDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'Distributes the landing page of codemonger'
        HttpVersion: 'http1.1'
        IPV6Enabled: true
        PriceClass: 'PriceClass_All'
        DefaultRootObject: 'index.html'
        Origins:
          - Id: !Sub '${AWS::StackName}-main-s3-bucket'
            DomainName: !Sub '${CodeMongerLandingPageBucket}.s3.${AWS::Region}.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CodeMongerLandingPageOriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: !Sub '${AWS::StackName}-main-s3-bucket'
          AllowedMethods:
            - 'GET'
            - 'HEAD'
            - 'OPTIONS'
          # ForwardedValues is deprecated but
          # a cache policy cannot be created by CloudFormation for now.
          ForwardedValues:
            QueryString: false
          DefaultTTL: 3600 # one hour
          ViewerProtocolPolicy: 'redirect-to-https'
        Aliases: !Ref LandingPageAliases
        ViewerCertificate:
          AcmCertificateArn: !Ref LandingPageDomainCertificateArn
          MinimumProtocolVersion: 'TLSv1.2_2018'
          SslSupportMethod: 'sni-only'
        Logging:
          Bucket: !GetAtt AccessLogBucket.DomainName
          Prefix: 'codemonger/'
          IncludeCookies: false
      Tags:
        - Key: 'project'
          Value: !Ref ProjectTag

  CodeMongerLandingPageOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Origin Access Identity user for the landing page of codemonger'

  AccessLogBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    Properties:
      AccessControl: 'LogDeliveryWrite'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
        - Key: 'project'
          Value: !Ref ProjectTag

Outputs:
  CodeMongerLandingPageBucketName:
    Description: 'Name of the bucket for the static contents of the landing page of codemonger'
    Value: !Ref CodeMongerLandingPageBucket
  AccessLogBucketName:
    Description: 'Name of the bucket for the access log of CloudFront'
    Value: !Ref AccessLogBucket
  CodeMongerLandingPageDomainName:
    Description: 'Domain name of the landing page of codemonger'
    Value: !GetAtt CodeMongerLandingPageDistribution.DomainName
  CodeMongerLandingPageUrl:
    Description: 'URL of the landing page of codemonger'
    Value: !Sub "https://${CodeMongerLandingPageDistribution.DomainName}/"
